<?php
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_53e9721065551',
	'title' => 'Inbound Pro',
	'fields' => array (
		array (
			'key' => 'field_53e97b30498c3',
			'label' => 'Main Settings',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
		),
		array (
			'key' => 'field_53e9721533fde',
			'label' => 'API Key',
			'name' => 'inbound_api_key',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_53e9727e9e244',
			'label' => 'Exclude IP Addresses',
			'name' => 'exclude_ip_addresses',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add I.P. Address Exclusion',
			'sub_fields' => array (
				array (
					'key' => 'field_53e972a29e245',
					'label' => 'IP',
					'name' => 'ip',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
			),
		),
		array (
			'key' => 'field_53f3f7cda2b6f',
			'label' => 'Lead Fields',
			'name' => 'lead_fields',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_53f3f7d5a2b70',
					'label' => 'Field Name',
					'name' => 'field_name',
					'prefix' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_53f3f7e6a2b71',
					'label' => 'Field Type',
					'name' => 'field_type',
					'prefix' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'column_width' => '',
					'choices' => array (
						'text' => 'text',
						'textarea' => 'textarea',
						'select' => 'select',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'disabled' => 0,
					'readonly' => 0,
				),
			),
		),
		array (
			'key' => 'field_53e97af52a178',
			'label' => 'Manage Addons',
			'name' => '',
			'prefix' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
		),
		array (
			'key' => 'field_53e97868f21e7',
			'label' => 'Manage Addons',
			'name' => 'Manage_Addons',
			'prefix' => '',
			'type' => 'MANAGE_INBOUND_ADDONS',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'font_size' => 14,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'inbound-pro-setting',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;