<?php
/**
* Template Name: Simple Responsive
* @package	Inbound Email
* 
*/

$key = basename(dirname(__FILE__));


/* Configures Template Information */
$inbound_email_data[$key]['info'] = array(
	'data_type' =>'email-template',
	'label' => __( 'Simple Basic' , 'inbound-pro') ,
	'category' => 'responsive',
	'demo' => '',
	'description' => __( 'Simple basic email template.' , 'inbound-pro' ),
	'acf' => true
);

/*
* Define ACF Fields to be used in this template
* Pay special attention to the 'location' key as this is where we tell ACF to load when this template is selected
*/

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55cd9b08e171d',
	'title' => __('Simple Basic','inbound-pro'),
	'fields' => array (
		array (
			'key' => 'field_55cd9b09ede91',
			'label' => __('Header','inbound-pro'),
			'name' => 'header',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55cd9b09ee279',
			'label' => __('Logo Image','inbound-pro'),
			'name' => 'logo_url',
			'type' => 'image',
			'instructions' => __('Enter or upload your logo here','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55cd9b09ee661',
			'label' => __('Header Background Color','inbound-pro'),
			'name' => 'header_bg_color',
			'type' => 'color_picker',
			'instructions' => __('Choose the background color of your header','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array (
			'key' => 'field_55cd9b09eea49',
			'label' => __('Email Body','inbound-pro'),
			'name' => 'email_body',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55cd9b09efdd1',
			'label' => __('Main Email Content','inbound-pro'),
			'name' => 'main_email_content',
			'type' => 'wysiwyg',
			'instructions' => __('The content of your email should go here.','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => __('Dear [lead-field id="wpleads_first_name" default="Subscriber"],

Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et.','inbound-pro'),
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_55cd9b09ef9e9',
			'label' => __('Callout Background Color','inbound-pro'),
			'name' => 'callout_bg_color',
			'type' => 'color_picker',
			'instructions' => __('Choose the callout background color','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#efefef',
		),
		array (
			'key' => 'field_55cd9b09ef601',
			'label' => __('Callout','inbound-pro'),
			'name' => 'callout',
			'type' => 'wysiwyg',
			'instructions' => __('Add here the callout content','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => __('Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt. <a href="#">Do it Now! »</a>','inbound-pro'),
			'tabs' => 'all',
			'toolbar' => 'basic',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_55cd9b09f098a',
			'label' => __('Social Box','inbound-pro'),
			'name' => 'social_box',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55cd9b09f0d72',
			'label' => __('Social Box Background Color','inbound-pro'),
			'name' => 'social_bg_color',
			'type' => 'color_picker',
			'instructions' => __('Choose the background color of the social box','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#efefef',
		),
		array (
			'key' => 'field_55cd9b09f115a',
			'label' => __('Facebook Page','inbound-pro'),
			'name' => 'facebook_page',
			'type' => 'text',
			'instructions' => __('Enter the URL of your Facebook page if you have one','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55cd9b09f1542',
			'label' => __('Twitter Handle','inbound-pro'),
			'name' => 'twitter_handle',
			'type' => 'text',
			'instructions' => __('Enter you Twitter handle here','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55cd9b09f192a',
			'label' => __('Google Plus','inbound-pro'),
			'name' => 'google_plus',
			'type' => 'text',
			'instructions' => __('Enter your Google Plus URL','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55cd9b09f1d12',
			'label' => __('Phone Number','inbound-pro'),
			'name' => 'phone_number',
			'type' => 'text',
			'instructions' => __('Enter your phone number here','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => __('1 555 555 5555','inbound-pro'),
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55cd9b09f20fa',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'instructions' => __('Enter your email here','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => __('user@example.com','inbound-pro'),
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_55cd9b09f24e2',
			'label' => __('Footer','inbound-pro'),
			'name' => 'footer',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55cd9b09f28caunl',
			'label' => __('Unsubscribe Link Anchor','inbound-pro'),
			'name' => 'unsubscribe_link_text',
			'type' => 'text',
			'instructions' => __('Enter the text of the unsubscribe link.','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => __('Unsubscribe','inbound-pro'),
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55cd9b09f28ca',
			'label' => __('Terms Page URL','inbound-pro'),
			'name' => 'terms_page_url',
			'type' => 'text',
			'instructions' => __('Enter the URL of your terms page here','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55cd9b09f2cb2',
			'label' => __('Privacy Page URL','inbound-pro'),
			'name' => 'privacy_page_url',
			'type' => 'text',
			'instructions' => __('Enter the URL of your privacy page here','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56b91774c2c42sb98',
			'label' => __('Hide \'Show this email in browser\' link','inbound-pro'),
			'name' => 'hide_show_email_in_browser',
			'type' => 'checkbox',
			'instructions' => __('Hide/Reveal the link to the online version of the email.','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'hide' => 'hide',
			),
			'default_value' => array (
			),
			'layout' => 'vertical',
			'toggle' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'inbound-email',
			),
			array (
					'param' => 'template_id',
					'operator' => '==',
					'value' => $key,
				)
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;