<?php
/**
* Template Name: Cerberus Fluid
* @package	Inbound Email
*
*/

$key = basename(dirname(__FILE__));

/* Configures Template Information */
$inbound_email_data[$key]['info'] = array(
	'data_type' =>'email-template',
	'label' => __( 'New Post Notification' , 'inbound-pro') ,
	'category' => 'responsive,automated',
	'demo' => '',
	'description' => __( 'Official template powering Inbound Now new post email.' , 'inbound-pro' ),
	'acf' => true
);

/*
* Define ACF Fields to be used in this template
* Pay special attention to the 'location' key as this is where we tell ACF to load when this template is selected
*/

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_577ec49be93acinnpnf',
	'title' => 'Inbound Now - New Post Notification Fields',
	'fields' => array (
		array (
			'key' => 'field_57805f3dcc0a9innpnf',
			'label' => __( 'Optional: Email Header Text','inbound-pro'),
			'name' => 'optional_email_header_text',
			'type' => 'text',
			'instructions' => __( 'Use this optional field to put in some headline text that will display in the inbox preview, but not in the email body','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'New content from {{site_name}}',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57805f3dcc0a9innpnfheader_text',
			'label' => __( 'Article Title / Headline','inbound-pro'),
			'name' => 'email_header_text',
			'type' => 'text',
			'instructions' => __( 'This will display below the featured image and above  Main Content A.','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{post_title}}',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577ec5521ab00innpnf',
			'label' => __( 'Logo Image','inbound-pro'),
			'name' => 'logo_image',
			'type' => 'image',
			'instructions' => __( 'Use this field to display your logo in the head of the email. The max width with 200px and the max height is 200px','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_577ec60a1ab01innpnf',
			'label' => __( 'Featured Image','inbound-pro'),
			'name' => 'featured_image',
			'type' => 'text',
			'instructions' => __( 'This is the main image of the email. The max width is 600px, with the height being scaled according to aspect ratio','inbound-pro' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{featured_image}}',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577ec67c1ab02innpnf',
			'label' => __( 'Main Content A','inbound-pro'),
			'name' => 'main_content_a',
			'type' => 'wysiwyg',
			'instructions' => __( 'This editor is for putting text based content above the email button','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{post_excerpt}}',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_577ec6dc1ab03innpnf',
			'label' => __( 'Email Button Text','inbound-pro'),
			'name' => 'email_button_text',
			'type' => 'text',
			'instructions' => __( 'Use this to change the displayed text on the email button','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Read Now',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577ec7821ab04innpnf',
			'label' => __( 'Email Button Link','inbound-pro'),
			'name' => 'email_button_link',
			'type' => 'text',
			'instructions' => __( 'Use this to set where the email button takes users after they click it','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{permalink}}',
			'placeholder' => '',
		),
		array (
			'key' => 'field_577eeb5c748f1innpnf',
			'label' => __( 'Email Button Text Color','inbound-pro'),
			'name' => 'email_button_text_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the color of the text in the email button','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array (
			'key' => 'field_577eeb01748f0innpnf',
			'label' => __( 'Email Button Color','inbound-pro'),
			'name' => 'email_button_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the color of the button in the email','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#222222',
		),
		array (
			'key' => 'field_577f3b2a78d08innpnf',
			'label' => __( 'Email Button Hover Color','inbound-pro'),
			'name' => 'email_button_hover_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the color of the email button when the mouse hovers over it','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#555555',
		),
		array (
			'key' => 'field_578004e0e675dinnpnf',
			'label' => __( 'Button Font size','inbound-pro'),
			'name' => 'button_font_size',
			'type' => 'text',
			'instructions' => __( 'Use this to change the font size of the button text','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '13px',
			'placeholder' => 'Use standard CSS font measurements, like: 13px, 1.4em',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577ec7f21ab05innpnf',
			'label' => __( 'Main Content B','inbound-pro'),
			'name' => 'main_content_b',
			'type' => 'wysiwyg',
			'instructions' => __( 'This editor is for putting text based content below the email button','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{post_content}}',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_5780048fe675binnpnf',
			'label' => __( 'Main Content Font Size','inbound-pro'),
			'name' => 'main_content_font_size',
			'type' => 'text',
			'instructions' => __( 'Use this to change the font size of the main content area. (Main Content A & B)', 'inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '15px',
			'placeholder' => 'Use standard CSS font measurements, like: 15px, 1.5em',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577eefd19cf41innpnf',
			'label' => __( 'Email Colors','inbound-pro'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_577ee73f748edinnpnf',
			'label' => __( 'Email Background Color','inbound-pro'),
			'name' => 'email_background_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to set the background color of the email. This is the overall background color, not the background for the email content', 'inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#222222',
		),
		array (
			'key' => 'field_577eea5e748eeinnpnf',
			'label' => __( 'Email Content Background Color','inbound-pro'),
			'name' => 'email_content_background_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the background color of the email\'s content','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array (
			'key' => 'field_577eeabf748efinnpnf',
			'label' => __( 'Email Text Color','inbound-pro'),
			'name' => 'email_text_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the color of the text in the email','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#555555',
		),
		array (
			'key' => 'field_577eee5f748f3innpnf',
			'label' => __( 'Contact Information','inbound-pro'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57844029e5864innpnf',
			'label' => __( 'Contact Information Content','inbound-pro'),
			'name' => 'contact_information_content',
			'type' => 'wysiwyg',
			'instructions' => __( 'Use this editor to put in your company\'s contact information', 'inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Email powered by <a href="https://inboundnow.com/" style="color:#fff;text-decoration:none;">Inbound Now</a> and <a href="https://www.SparkPost.com/" style="font-color:#fff;text-decoration:none;">SparkPost</a>',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_577eee34748f2innpnf',
			'label' => __( 'Contact Information Text Color','inbound-pro'),
			'name' => 'contact_information_text_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the color of the contact information.','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#888888',
		),
		array (
			'key' => 'field_57800750e675einnpnf',
			'label' => __( 'Contact Information Font Size','inbound-pro'),
			'name' => 'contact_information_font_size',
			'type' => 'text',
			'instructions' => __( 'Use this to change the font size of the contact information','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '12px',
			'placeholder' => 'Use standard CSS font measurements, like: 12px, 1.3em',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577f24996f960innpnf',
			'label' => __( 'Unsubscribe Link Text','inbound-pro'),
			'name' => 'unsubscribe_link_text',
			'type' => 'text',
			'instructions' => __( 'Use this to change the text of the "unsubscribe" link','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Unsubscribe',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57800c078fe56innpnf',
			'label' => __( 'Unsubscribe Link Color','inbound-pro'),
			'name' => 'unsubscribe_link_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the color of the "unsubscribe" link','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#888888',
		),
		array (
			'key' => 'field_578449eab4deainnpnf',
			'label' => __( 'Unsubscribe Link Text Size','inbound-pro'),
			'name' => 'unsubscribe_link_text_size',
			'type' => 'text',
			'instructions' => __( 'Use this to change the font size of the "unsubscribe" link','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '12px',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577eee5f748f3innpnfaditionaloptions',
			'label' => __( 'Additional Options','inbound-pro'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56b8fa8acadf1show_latest_posts',
			'label' => __( 'Show Latest Posts','inbound-pro'),
			'name' => 'show_latest_posts',
			'type' => 'select',
			'instructions' => __( 'Set to yes to show latest posts.','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'no' => 'no',
				'yes' => 'yes',
			),
			'default_value' => array (
				'no' => 'yes',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56b8fa8acadf1set_category',
			'label' => __( 'Focus Category','inbound-pro'),
			'name' => 'show_latest_posts_category',
			'type' => 'taxonomy',
			'taxonomy' => 'taxonomy',
			'field_type' => 'multi_select',
			'instructions' => __( 'Select which categories to pull posts from.','inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'allow_null' => 1,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_56b8fa8acalimitpost',
			'label' => __( 'Limit posts','inbound-pro'),
			'name' => 'show_latest_posts_limit',
			'type' => 'number',
			'default_value' => '5',
			'instructions' => __( 'Select which categories to pull posts from.', 'inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_577ec6dc1ab03keepreading',
			'label' => __( 'Keep Reading Button Text','inbound-pro'),
			'name' => 'posts_button_text',
			'type' => 'text',
			'instructions' => __( 'Use this to change the displayed text on "Keep Reading" buttons', 'inbound-pro' ),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Learn More',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577eeb01748f0innpnfx1',
			'label' => __( 'Keep Reading Button BG Color','inbound-pro'),
			'name' => 'posts_button_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the color of the button in the email', 'inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#eacb3c',
		),
		array (
			'key' => 'field_577eeb01748f0innpnfx2',
			'label' => __( 'Keep Reading Button Text Color','inbound-pro'),
			'name' => 'posts_button_text_color',
			'type' => 'color_picker',
			'instructions' => __( 'Use this to change the color of the text inside the button', 'inbound-pro'),
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#282828',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'inbound-email',
			),
			array (
				'param' => 'template_id',
				'operator' => '==',
				'value' => 'new-post-notification',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
