<?php
/**
* Template Name: Sidebar
* @package	Inbound Email
* 
*/

$key = basename(dirname(__FILE__));


/* Configures Template Information */
$inbound_email_data[$key]['info'] = array(
	'data_type' =>'email-template',
	'label' => __( 'Sidebar' , 'inbound-mailer') ,
	'category' => 'responsive',
	'demo' => '',
	'description' => __( 'Sidebar email template.' , 'inbound-mailer' ),
	'acf' => true
);

/*
* Define ACF Fields to be used in this template
* Pay special attention to the 'location' key as this is where we tell ACF to load when this template is selected
*/
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55cc433477c28',
	'title' => 'Sidebar',
	'fields' => array (
		array (
			'key' => 'field_55cd81a2fc784',
			'label' => 'Header',
			'name' => 'header',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55cc4334a8973',
			'label' => 'Logo',
			'name' => 'logo_url',
			'type' => 'image',
			'instructions' => 'Enter or upload your logo here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_55d4b1c84db5f',
			'label' => 'Header Background Color',
			'name' => 'header_bg_color',
			'type' => 'color_picker',
			'instructions' => 'Choose the background color of your header',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#e6e6e6',
		),
		array (
			'key' => 'field_55cc44eecaab2',
			'label' => 'Email Body',
			'name' => 'main_content',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55d4967d8a0c4',
			'label' => 'Email Body',
			'name' => 'email_body',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Row',
			'min' => 1,
			'max' => '',
			'layouts' => array (
				array (
					'key' => '55d4968a71fb8',
					'name' => 'email_content',
					'label' => 'Email content',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_55cc4334a8d5b',
							'label' => 'Content',
							'name' => 'main_content',
							'type' => 'wysiwyg',
							'instructions' => 'The content of your email should go here.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Dear [lead-field id="wpleads_first_name" default="Subscriber"],
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et.</p>
<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque sollicitudin magna vitae erat vehicula, nec dapibus libero suscipit. Duis rhoncus turpis id maximus malesuada. Sed ultricies ex quis nisl malesuada, in feugiat libero commodo. Nam vitae lorem euismod, scelerisque purus non, feugiat ante. Vestibulum mollis metus vitae maximus pulvinar. Donec vitae tellus porttitor, ullamcorper est non, euismod mauris. Aenean ante neque, porta eu mi sed, vehicula accumsan sem. Pellentesque et velit non eros lobortis ultricies sed a justo. Aliquam id turpis magna. Duis finibus interdum tortor, lacinia mattis ligula imperdiet at. Vivamus lacinia eros eget nunc ultrices hendrerit. Curabitur lobortis et lorem ut viverra. Pellentesque at nulla mi. Phasellus hendrerit porttitor est nec tempor. Etiam in pellentesque lacus.</p>

<p>Fusce aliquam, neque in congue euismod, dui ligula sagittis lorem, sed egestas ante neque in risus. Sed convallis ipsum ut mauris mattis rhoncus. Aenean ac nisi at risus pulvinar mattis eu eget turpis. Donec eu purus nec orci suscipit fermentum quis ut metus. Fusce aliquam semper tempus. Sed convallis elementum pellentesque. Proin orci enim, vehicula vel lectus eget, faucibus pretium velit.</p>

<p>Etiam id aliquet justo, non interdum eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Fusce nec nisi pellentesque, dignissim diam sit amet, ornare neque. In sollicitudin sagittis nibh, eu interdum mi imperdiet eget. Proin vitae lacus sed lorem posuere facilisis et viverra velit. Aliquam porttitor maximus turpis, at iaculis orci ullamcorper sed. Aliquam non volutpat enim, at lobortis nibh. Duis vestibulum commodo diam quis cursus. Maecenas volutpat metus nunc, auctor vehicula quam fermentum vel. Vivamus sit amet nulla bibendum, accumsan erat eget, aliquet urna. Pellentesque id ultrices metus. Donec elementum ligula sed eros sodales interdum vitae in nibh. .</p>',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
					),
					'min' => 1,
					'max' => '',
				),
				array (
					'key' => '55d49e579fd52',
					'name' => 'button',
					'label' => 'Button',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_55cc4334a9cfb',
							'label' => 'Button Link',
							'name' => 'button_link',
							'type' => 'url',
							'instructions' => 'Add the link to a landing page',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_55cc4334aa0e4',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => 'Add the text that will appear inside the button',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_55d49e8a9fd53',
							'label' => 'Button Background Color',
							'name' => 'button_bg_color',
							'type' => 'color_picker',
							'instructions' => 'Choose the background color of your button',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#e6e6e6',
						),
						array (
							'key' => 'field_55d49efd9fd54',
							'label' => 'Button Text Color',
							'name' => 'button_text_color',
							'type' => 'color_picker',
							'instructions' => 'Choose the text color of your button',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#222222',
						),
					),
					'min' => '',
					'max' => '',
				),
				array (
					'key' => '55d49f4d6c45d',
					'name' => 'callout',
					'label' => 'Callout',
					'display' => 'row',
					'sub_fields' => array (
						array (
							'key' => 'field_55cc4334a9143',
							'label' => 'Callout Text',
							'name' => 'callout_text',
							'type' => 'wysiwyg',
							'instructions' => 'Add your callout text here',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.
<a href="#">Do it Now! »</a>',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
						),
						array (
							'key' => 'field_55cc4334a952b',
							'label' => 'Callout Background Color',
							'name' => 'callout_bg_color',
							'type' => 'color_picker',
							'instructions' => 'Choose the background color of the callout',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '#ecf8ff',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
		array (
			'key' => 'field_55cc455ccaab4',
			'label' => 'Social Box',
			'name' => 'footer',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55cc4334ab084',
			'label' => 'Social Box Background Color',
			'name' => 'footer_bg_color',
			'type' => 'color_picker',
			'instructions' => 'Choose the background color of the social box',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#e6e6e6',
		),
		array (
			'key' => 'field_55cc4334aa4cc',
			'label' => 'Facebook Page',
			'name' => 'facebook_page',
			'type' => 'url',
			'instructions' => 'Enter the URL of your Facebook page if you have one',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Enter the complete URL',
		),
		array (
			'key' => 'field_55cc4334aa8b4',
			'label' => 'Twitter Handle',
			'name' => 'twitter_handle',
			'type' => 'url',
			'instructions' => 'Enter you Twitter handle here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add the complete URL here',
		),
		array (
			'key' => 'field_55cc4334aac9c',
			'label' => 'Google Plus',
			'name' => 'google_plus',
			'type' => 'url',
			'instructions' => 'Enter your Google Plus URL',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add the complete URL',
		),
		array (
			'key' => 'field_55cc4334ab46c',
			'label' => 'Phone Number',
			'name' => 'phone_number',
			'type' => 'text',
			'instructions' => 'Enter your phone number here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55cc4334ab854',
			'label' => 'Email',
			'name' => 'email',
			'type' => 'email',
			'instructions' => 'Enter your email here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_55cc4524caab3',
			'label' => 'Sidebar',
			'name' => 'sidebar',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55cc4334ac40c',
			'label' => 'Sidebar Section',
			'name' => 'sidebar',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'In the following section you will add your sidebar content. A sidebar is be composed by one or many widget areas, each with a header, subheader and link sections.',
			'esc_html' => 0,
		),
		array (
			'key' => 'field_55cc4cf88ee15',
			'label' => 'Sidebar Background Color',
			'name' => 'sidebar_bg_color',
			'type' => 'color_picker',
			'instructions' => 'Choose the background color of your sidebar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#e6e6e6',
		),
		array (
			'key' => 'field_55cc4334ac7f4',
			'label' => 'Sidebar Header',
			'name' => 'sidebar_header',
			'type' => 'text',
			'instructions' => 'This is the header on top of your sidebar',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Header Thing »',
			'placeholder' => 'Add Here Your Sidebar Header',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55cc4334acbdc',
			'label' => 'Sidebar Subheader',
			'name' => 'sidebar_subheader',
			'type' => 'text',
			'instructions' => 'Here you should add the subheader that will show up under the sidebar header. Leave the field empty if you don\'t want one',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Add Here the sidebar Subheader',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55d4ab3d88fe5',
			'label' => 'Sidebar Header URL',
			'name' => 'sidebar_header_url',
			'type' => 'url',
			'instructions' => 'The URL link of the sidebar header. Leave the default value if you don\'t want a link',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55d005a26a3a9',
			'label' => 'Sidebar Link Sections',
			'name' => 'sidebar_sections',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => 1,
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Link Section',
			'sub_fields' => array (
				array (
					'key' => 'field_55d005e429b2f',
					'label' => 'Section Link Text',
					'name' => 'section_link_text',
					'type' => 'text',
					'instructions' => 'Here you should add the text of your link',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_55d00632b9d71',
					'label' => 'Section Link URL',
					'name' => 'section_link_url',
					'type' => 'url',
					'instructions' => 'Here you should add the URL of the link',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => 'Add the complete URL',
				),
			),
		),
		array (
			'key' => 'field_55cd6cf637faa',
			'label' => 'Footer',
			'name' => 'footer',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_55cc4334abc3c',
			'label' => 'Terms Page URL',
			'name' => 'terms_page_url',
			'type' => 'url',
			'instructions' => 'Enter the URL of your terms page here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_55cc4334ac024',
			'label' => 'Privacy Page URL',
			'name' => 'privacy_page_url',
			'type' => 'url',
			'instructions' => 'Enter the URL of your privacy page here',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'inbound-email',
			),
			array (
				'param' => 'template_id',
				'operator' => '==',
				'value' => $key,
			)
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;