<?php
/**
* Template Name: Cerberus Fluid
* @package	Inbound Email
*
*/

$key = basename(dirname(__FILE__));

/* Configures Template Information */
$inbound_email_data[$key]['info'] = array(
	'data_type' =>'email-template',
	'label' => __( 'New Post Notification' , 'inbound-pro') ,
	'category' => 'responsive,automated',
	'demo' => '',
	'description' => __( 'Official template powering Inbound Now new post email.' , 'inbound-pro' ),
	'acf' => true
);

/*
* Define ACF Fields to be used in this template
* Pay special attention to the 'location' key as this is where we tell ACF to load when this template is selected
*/

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_577ec49be93acinnpnf',
	'title' => 'Inbound Now - New Post Notification Fields',
	'fields' => array (
		array (
			'key' => 'field_57805f3dcc0a9innpnf',
			'label' => 'Optional: Email Header Text',
			'name' => 'optional_email_header_text',
			'type' => 'text',
			'instructions' => 'Use this optional field to put in some headline text that will display in the inbox preview, but not in the email body',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'New content from {{site_name}}',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57805f3dcc0a9innpnfheader_text',
			'label' => 'Article Title / Headline',
			'name' => 'email_header_text',
			'type' => 'text',
			'instructions' => 'This will display below the featured image and above  Main Content A.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{post_title}}',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577ec5521ab00innpnf',
			'label' => 'Logo Image',
			'name' => 'logo_image',
			'type' => 'image',
			'instructions' => 'Use this field to display your logo in the head of the email. The max width with 200px and the max height is 200px',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_577ec60a1ab01innpnf',
			'label' => 'Featured Image',
			'name' => 'featured_image',
			'type' => 'text',
			'instructions' => 'This is the main image of the email. The max width is 600px, with the height being scaled according to aspect ratio',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{featured_image}}',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577ec67c1ab02innpnf',
			'label' => 'Main Content A',
			'name' => 'main_content_a',
			'type' => 'wysiwyg',
			'instructions' => 'This editor is for putting text based content above the email button',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{post_excerpt}}',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_577ec6dc1ab03innpnf',
			'label' => 'Email Button Text',
			'name' => 'email_button_text',
			'type' => 'text',
			'instructions' => 'Use this to change the displayed text on the email button',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Read Now',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577ec7821ab04innpnf',
			'label' => 'Email Button Link',
			'name' => 'email_button_link',
			'type' => 'text',
			'instructions' => 'Use this to set where the email button takes users after they click it',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{permalink}}',
			'placeholder' => '',
		),
		array (
			'key' => 'field_577eeb5c748f1innpnf',
			'label' => 'Email Button Text Color',
			'name' => 'email_button_text_color',
			'type' => 'color_picker',
			'instructions' => 'Use this to change the color of the text in the email button',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array (
			'key' => 'field_577eeb01748f0innpnf',
			'label' => 'Email Button Color',
			'name' => 'email_button_color',
			'type' => 'color_picker',
			'instructions' => 'Use this to change the color of the button in the email',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#222222',
		),
		array (
			'key' => 'field_577f3b2a78d08innpnf',
			'label' => 'Email Button Hover Color',
			'name' => 'email_button_hover_color',
			'type' => 'color_picker',
			'instructions' => 'Use this to change the color of the email button when the mouse hovers over it',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#555555',
		),
		array (
			'key' => 'field_578004e0e675dinnpnf',
			'label' => 'Button Font size',
			'name' => 'button_font_size',
			'type' => 'text',
			'instructions' => 'Use this to change the font size of the button text',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '13px',
			'placeholder' => 'Use standard CSS font measurements, like: 13px, 1.4em',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577ec7f21ab05innpnf',
			'label' => 'Main Content B',
			'name' => 'main_content_b',
			'type' => 'wysiwyg',
			'instructions' => 'This editor is for putting text based content below the email button',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '{{post_content}}',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_5780048fe675binnpnf',
			'label' => 'Main Content Font Size',
			'name' => 'main_content_font_size',
			'type' => 'text',
			'instructions' => 'Use this to change the font size of the main content area. (Main Content A & B)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '15px',
			'placeholder' => 'Use standard CSS font measurements, like: 15px, 1.5em',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577eefd19cf41innpnf',
			'label' => 'Email Colors',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_577ee73f748edinnpnf',
			'label' => 'Email Background Color',
			'name' => 'email_background_color',
			'type' => 'color_picker',
			'instructions' => 'Use this to set the background color of the email. This is the overall background color, not the background for the email content',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#222222',
		),
		array (
			'key' => 'field_577eea5e748eeinnpnf',
			'label' => 'Email Content Background Color',
			'name' => 'email_content_background_color',
			'type' => 'color_picker',
			'instructions' => 'Use this to change the background color of the email\'s content',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
		),
		array (
			'key' => 'field_577eeabf748efinnpnf',
			'label' => 'Email Text Color',
			'name' => 'email_text_color',
			'type' => 'color_picker',
			'instructions' => 'Use this to change the color of the text in the email',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#555555',
		),
		array (
			'key' => 'field_577eee5f748f3innpnf',
			'label' => 'Contact Information',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_57844029e5864innpnf',
			'label' => 'Contact Information Content',
			'name' => 'contact_information_content',
			'type' => 'wysiwyg',
			'instructions' => 'Use this editor to put in your company\'s contact information',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Email powered by <a href="https://inboundnow.com/" style="font-color:#fff;text-decoration:none;">Inbound Now</a> and <a href="https://www.SparkPost.com/" style="font-color:#fff;text-decoration:none;">SparkPost</a>',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
		),
		array (
			'key' => 'field_577eee34748f2innpnf',
			'label' => 'Contact Information Text Color',
			'name' => 'contact_information_text_color',
			'type' => 'color_picker',
			'instructions' => 'Use this to change the color of the contact information.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#888888',
		),
		array (
			'key' => 'field_57800750e675einnpnf',
			'label' => 'Contact Information Font Size',
			'name' => 'contact_information_font_size',
			'type' => 'text',
			'instructions' => 'Use this to change the font size of the contact information',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '12px',
			'placeholder' => 'Use standard CSS font measurements, like: 12px, 1.3em',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577f24996f960innpnf',
			'label' => 'Unsubscribe Link Text',
			'name' => 'unsubscribe_link_text',
			'type' => 'text',
			'instructions' => 'Use this to change the text of the "unsubscribe" link',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Unsubscribe from this list',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_57800c078fe56innpnf',
			'label' => 'Unsubscribe Link Color',
			'name' => 'unsubscribe_link_color',
			'type' => 'color_picker',
			'instructions' => 'Use this to change the color of the "unsubscribe" link',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#888888',
		),
		array (
			'key' => 'field_578449eab4deainnpnf',
			'label' => 'Unsubscribe Link Text Size',
			'name' => 'unsubscribe_link_text_size',
			'type' => 'text',
			'instructions' => 'Use this to change the font size of the "unsubscribe" link',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '12px',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_577eee5f748f3innpnfaditionaloptions',
			'label' => 'Additional Options',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_56b8fa8acadf1show_latest_posts',
			'label' => 'Show Latest Posts',
			'name' => 'show_latest_posts',
			'type' => 'select',
			'instructions' => 'Set to yes to show latest posts.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'no' => 'no',
				'yes' => 'yes',
			),
			'default_value' => array (
				'no' => 'yes',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
			'disabled' => 0,
			'readonly' => 0,
		),
		array (
			'key' => 'field_56b8fa8acadf1set_category',
			'label' => 'Focus Category',
			'name' => 'show_latest_posts_category',
			'type' => 'taxonomy',
			'taxonomy' => 'taxonomy',
			'field_type' => 'multi_select',
			'instructions' => 'Select which categories to pull posts from.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'category',
			'allow_null' => 1,
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'multiple' => 0,
		),
		array (
			'key' => 'field_56b8fa8acalimitpost',
			'label' => 'Limit posts',
			'name' => 'show_latest_posts_limit',
			'type' => 'number',
			'default_value' => '5',
			'instructions' => 'Select which categories to pull posts from.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'multiple' => 0,
		),

		array (
			'key' => 'field_577ec6dc1ab03keepreading',
			'label' => 'Keep Reading Button Text',
			'name' => 'posts_button_text',
			'type' => 'text',
			'instructions' => 'Use this to change the displayed text on "Keep Reading" buttons',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Learn More',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'inbound-email',
			),
			array (
				'param' => 'template_id',
				'operator' => '==',
				'value' => 'new-post-notification',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
